site_name: ss
nav: 
    - linux编程:
        - linux编程/index.md
        - linux编程/make命令.md
        - linux编程/GCC linux.md
    - IO Redirection:
        - IO Redirection/index.md
        - IO Redirection/lnput Redirection.md
        - IO Redirection/Output Redirection.md
        - IO Redirection/Error Redirection.md
    - unix Tools:
        - unix Tools/index.md
        - unix Tools/Find.md
        - unix Tools/Locate.md
        - unix Tools/Date.md
        - unix Tools/Cal.md
        - unix Tools/Sleep.md
        - unix Tools/Time.md
        - unix Tools/zcat&zmore.md
        - unix Tools/bzip2&bunzip2.md
        - unix Tools/bzcat&bzmore.md
        - unix Tools/df.md
    - regex正则表达式:
        - regex正则表达式/index.md
        - regex正则表达式/expr命令.md
        - regex正则表达式/RegEx.md
        - regex正则表达式/Grep RegEx.md
        - regex正则表达式/rename RegEx.md
        - regex正则表达式/Sed RegEx.md
    - Security:
        - Security/index.md
        - Security/File OwnerShip.md
        - Security/chgrp.md
        - Security/Permission.md
        - Security/chmod.md
        - Security/chown.md
        - Security/Advance Permission.md
        - Security/File Links.md
        - Security/1) lnodes.md
        - Security/2) Link Directories.md
        - Security/3) Hard links.md
        - Security/4) Soft links.md
        - Security/5) Remove link.md
    - Networking:
        - Networking/index.md
        - Networking/1）ifconfig.md
        - Networking/2）ip.md
        - Networking/telnet.md
        - Networking/SSH.md
        - Networking/mail.md
        - Networking/3) traceroute.md
        - Networking/4) tracepath.md
        - Networking/5) ping.md
        - Networking/6) netstat.md
        - Networking/7) ss.md
        - Networking/8) dig.md
        - Networking/9) nslookup.md
        - Networking/10) route.md
        - Networking/11) host.md
        - Networking/12) arp.md
        - Networking/13) iwconfig.md
        - Networking/14) hostname.md
        - Networking/15) curl&wget.md
        - Networking/Curl Command.md
        - Networking/16) mtr.md
        - Networking/17) whois.md
        - Networking/18) ifplugstatus.md
    - editor:
        - editor/index.md
        - editor/vi.md
    - System Admin:
        - System Admin/index.md
        - System Admin/Admin Commands.md
        - System Admin/uptime.md
        - System Admin/service.md
        - System Admin/pmap.md
        - System Admin/wget command.md
        - System Admin/ftp&sftp.md
        - System Admin/free.md
        - System Admin/top.md
        - System Admin/last.md
        - System Admin/ps.md
        - System Admin/shutdown.md
        - System Admin/info.md
        - System Admin/env.md
        - System Admin/du.md
        - System Admin/init.md
        - System Admin/Nano编辑器.md
        - System Admin/shred.md
        - System Admin/mount.md
        - System Admin/route.md
    - man:
        - man/index.md
        - man/man -a.md
        - man/man -aw.md
        - man/man -f.md
        - man/man -k(apropos).md
        - man/man whereis.md
        - man/Whatis.md
    - 错误码:
        - 错误码/index.md
        - 错误码/错误码.md
    - misc:
        - misc/index.md
        - misc/杂项.md
        
extra_css:
    - res/extra.css
extra_javascript:
    - res/extra.js

    - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js

    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: Copyright &copy; 2022 - 2023 travis

# repo_url: @
# repo_name: @

theme:
    name: material
    # custom_dir: overrides

    palette:
        - media: "(prefers-color-scheme)"
          primary: red
          accent: red
          toggle:
            icon: material/brightness-auto
            name: 切换到暗模式
        - media: "(prefers-color-scheme: light)"
          primary: green
          accent: green
          scheme: default 
          toggle:
            icon: material/brightness-7
            name: 切换到默认模式
        - media: "(prefers-color-scheme: dark)"
          primary: blue
          accent: blue
          scheme: slate
          toggle:
            icon: material/brightness-4
            name: 切换到亮模式

    font:
        text: Roboto
        code: Roboto Mono

    language: zh
    direction: ltr

    logo: https://pic.peo.pw/a/2023/01/12/63bfb934b1b06.png
    favicon: https://pic.peo.pw/a/2023/01/12/63bfb934b1b06.png
    icon:
        logo: octicons/heart-fill-24

        repo: fontawesome/brands/github
        edit: material/pencil
        view: material/eye


        admonition:
            note: fontawesome/solid/note-sticky
            abstract: fontawesome/solid/book
            info: fontawesome/solid/circle-info
            tip: fontawesome/solid/bullhorn
            success: fontawesome/solid/check
            question: fontawesome/solid/circle-question
            warning: fontawesome/solid/triangle-exclamation
            failure: fontawesome/solid/bomb
            danger: fontawesome/solid/skull
            bug: fontawesome/solid/robot
            example: fontawesome/solid/flask
            quote: fontawesome/solid/quote-left




    features:
        - navigation.instant
        - navigation.tracking
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.sections
        # - navigation.expand
        - navigation.prune
        - navigation.indexes
        - toc.follow
        # - toc.integrate
        - navigation.top

        - search.suggest
        - search.highlight
        - search.share

        - header.autohide

        - navigation.footer

        - content.action.edit
        - content.action.view

        - content.code.copy
        - content.code.annotate

        - content.tooltips


extra:
    alternate:
        - name: English
          link: /en/ 
          lang: en
        - name: 中文
          link: /zh/
          lang: zh

    homepage: /

    #consent:
    #    title: cookie
    #    description:    >-
    #        sdd
    #    cookies:
    #        analytics:
    #            github


    social:
        - icon: fontawesome/brands/github
          link: 链接url地址
          name: 标识名
        - icon: fontawesome/brands/docker
          link: 链接url地址
          name: 标识名
    generator: false


plugins:
    - search:
        lang:
            - en
            - ja
        # '[\s\-,:!=\[\]]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
        separator: '[\s\-\.]+'
        jieba_dict: res/dict.txt
        jieba_dict_user: res/user_dict.txt
    - search:
        lang:
            - en
        jieba_dict: dict/dict.txt
        separator: '[\s\-\.]+'
    # - typeset

    - glightbox

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences

    - attr_list
    - md_in_html
    - pymdownx.superfences

    - attr_list

    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences

    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    #- pymdownx.tabbed:
    #    slugify: !!python/object/apply:pymdownx.slugs.slugify
    #        kwds:
    #            case: lower

    # - content.tabs.link


    - tables
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
    - footnotes

    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde

    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg


    - attr_list
    - md_in_html

    - def_list
    - pymdownx.tasklist:
        custom_checkbox: true

    - pymdownx.arithmatex:
        generic: true

    - abbr
    - attr_list
    - pymdownx.snippets
    - pymdownx.snippets:
        auto_append:
            - includes/abbr.md

